project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - href: about.qmd 
        text: About  
      - href: projects.qmd 
        text: Projects 
      - href: work experience.qmd 
        text: Work Experience 
      - href: Education.qmd  
        text: Education 

  page-footer: 
      right: "&copy; 2024, Noor Benny" 


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 
    

execute: 
  freeze: auto 



