---
title: "Work Experience"
--- 

## Administrative Assistant 

*UCLA Conferences & Catering | Feb 2023 - Present | Los Angeles, California, United States* 

I provide administrative support to UCLA Conferences and Catering by accurately entering information into databases, preparing forms, reports, and memos, updating invoice and employee files, reconciling ledgers, and performing daily rounds on campus. Additionally, I provide support with photocopying, data entry, and distributing and picking up materials. I interact with staff and students at all levels of the organization and various campus departments, while maintaining confidentiality. 

Accomplishments: 

- Facilitated confidential client interactions, ensuring satisfaction while scheduling multi-day events

- Managed contract processing through UCLA Events Online (EOL), confirming venue reservations and adhering to company policies.

- Spearheaded accurate data entry into Salesforce, collaborating with staff, students, and clients of all levels. 

## Data-Driven Brand Marketing Intern 

*Orenda Marketing | Jun 2023 - Aug 2023 | Los Angeles, California, United States* 

I was responsible for assisting in conducting market research to stay on top of trends and best practices. I provide analytics support for client accounts and agency marketing efforts. Additionally, I conduct competitive analysis and report on findings, helping inform strategic decision-making. My role also involves developing and maintaining client reports, ensuring accurate and actionable information is delivered. Collaborating with the co-founders, I actively contribute to the development and refinement of the data-driven agency strategy. With my statistics and data science background, I play a key role in keeping the agency ahead of the curve with emerging marketing trends. Alongside these core responsibilities, I am always ready to assist with general administrative tasks and take on additional duties as needed. 

Accomplishments: 

- Conducted comprehensive market research on rival companies, providing valuable insights for strategic planning and decision-making.

- Developed and delivered weekly presentation decks, effectively communicating complex data and findings to stakeholders.

- Analyzed data across various marketing platforms, notably Google Analytics, contributing to the creation of impactful case studies published on the company website.

- Attained Google Analytics certification, enhancing proficiency in data analytics and contributing expertise to the marketing team's efforts. 

## Digital Marketing Intern 

*Meta | Jun 2022 - Sep 2022 | Monterey, California* 

I partnered with a small businesses in an underserved community in a fellowship in Digital Marketing. I learned from Meta educational, online courses and took the Meta certification exam for a Digital Marketing Associate to qualify my skillset. During the 12-week summer Fellowship, a I received mentorship from a Meta employee, ongoing training, and tech support to help me succeed on the job.

Accomplishments: 

- Enhanced online visibility and impact for small businesses post-training with Meta employees through comprehensive online courses.

- Achieved a notable increase in business's Instagram metrics: amplified follower engagement by 38%, expanded reach by 9.5%, and boosted total followers by 14.5%.

- Provided consistent updates to employers through detailed visual presentations in weekly progress reports.

- Compiled a comprehensive multi-page document detailing future strategies for sustained digital marketing efforts, benefiting the company's continued presence and growth on digital platforms.

## Math Tutor  

*Monterey Peninsula College | Jan 2022 - May 2022 | Monterey, California* 

I tutored college students in math subjects, including: Algebra, Statistics, Pre-Calculus, and Calculus to help them improve their understanding of specific topics. I worked with various learning levels and learned to adapt teach methods to effectively improve their understanding of a topic. I provided supplemental resources to students to aid with understanding of the given material resulting in grade improvement and progress to next class. 












